@csrf
<div class="row g-3">
  <div class="col-md-6"><label class="form-label" for="name">Full name</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $user->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $user->email ?? '') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="phone">Phone</label><input class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" value="{{ old('phone', $user->phone ?? '') }}">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="role">Role</label><select class="form-select @error('role') is-invalid @enderror" id="role" name="role" required>@foreach ($roles as $role)<option value="{{ $role }}" @selected(old('role', $user->role ?? 'student') === $role)>{{ str_replace('_', ' ', ucfirst($role)) }}</option>@endforeach</select>@error('role')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required><option value="active" @selected(old('status', $user->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $user->status ?? '') === 'inactive')>Inactive</option></select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="password">{{ isset($user) ? 'New password' : 'Password' }}</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" {{ isset($user) ? '' : 'required' }}><div class="form-text">Minimum 8 characters{{ isset($user) ? '; leave blank to keep the current password.' : '.' }}</div>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" {{ isset($user) ? '' : 'required' }}></div>
</div>
