@extends('layouts.app')
@section('title', 'User Management')
@section('content')
<section class="page-head"><div class="container"><nav aria-label="breadcrumb"><ol class="breadcrumb small mb-2"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Administration</a></li><li class="breadcrumb-item active">Users</li></ol></nav><div class="d-flex justify-content-between align-items-center"><div><h1 class="mb-1">User Management</h1><p class="text-muted mb-0">Search, filter and manage school accounts.</p></div><a class="btn btn-sv" href="{{ route('admin.users.create') }}">Add user</a></div></div></section>
<section class="section"><div class="container">
  @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
  <form class="row g-3 mb-4" method="GET"><div class="col-lg-5"><label class="form-label" for="search">Search</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Name, email or phone"></div><div class="col-md-3 col-lg-2"><label class="form-label" for="role">Role</label><select class="form-select" id="role" name="role"><option value="">All roles</option>@foreach ($roles as $role)<option value="{{ $role }}" @selected(request('role') === $role)>{{ str_replace('_', ' ', ucfirst($role)) }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All statuses</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select></div><div class="col-md-3 col-lg-2 d-flex align-items-end"><button class="btn btn-sv w-100" type="submit">Filter</button></div><div class="col-md-3 col-lg-1 d-flex align-items-end"><a class="btn btn-sv-outline w-100" href="{{ route('admin.users.index') }}">Reset</a></div></form>
  <div class="table-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Name</th><th>Phone</th><th>Role</th><th>Status</th><th>Created</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse ($users as $user)<tr><td><a href="{{ route('admin.users.show', $user) }}">{{ $user->name }}</a><div class="small text-muted">{{ $user->email }}</div></td><td>{{ $user->phone ?: '-' }}</td><td>{{ str_replace('_', ' ', ucfirst($user->role)) }}</td><td><span class="badge {{ $user->isActive() ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst($user->status) }}</span></td><td>{{ $user->created_at?->format('d M Y') }}</td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.users.edit', $user) }}">Edit</a><form class="d-inline" method="POST" action="{{ route('admin.users.status', $user) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning" type="submit">{{ $user->isActive() ? 'Deactivate' : 'Activate' }}</button></form>@if (auth()->id() !== $user->id)<form class="d-inline" method="POST" action="{{ route('admin.users.destroy', $user) }}" onsubmit="return confirm('Delete this user?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Delete</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center py-5">No users match your filters.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $users->links() }}</div></div>
</div></section>
@endsection
