@extends('layouts.app')
@section('title', 'Profile')
@section('content')
<section class="page-head"><div class="container"><a href="{{ route('admin.dashboard') }}">Management</a><h1>{{ str_replace('-', ' ', ucfirst($type)) }}</h1></div></section>
<section class="section"><div class="container"><div class="form-card">
@if($type === 'student-edit')<form method="POST" action="{{ route('admin.students.update',$record) }}">@csrf @method('PUT')<div class="row g-3">@foreach([['name','Full Name','text',$record->user->name],['email','Email','email',$record->user->email],['phone','Phone Number','text',$record->user->phone],['admission_number','Admission Number','text',$record->admission_number],['date_of_birth','Date of Birth','date',$record->date_of_birth?->format('Y-m-d')],['admission_date','Admission Date','date',$record->admission_date?->format('Y-m-d')],['roll_number','Roll Number','text',$record->roll_number]] as [$field,$label,$typeInput,$value])<div class="col-md-6"><label class="form-label" for="edit_student_{{ $field }}">{{ $label }}</label><input class="form-control" id="edit_student_{{ $field }}" name="{{ $field }}" type="{{ $typeInput }}" value="{{ $value }}"></div>@endforeach<div class="col-md-6"><label class="form-label" for="edit_student_class">Class</label><select class="form-select" id="edit_student_class" name="school_class_id"><option value="">Select class</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected($record->school_class_id === $class->id)>{{ $class->name }} ({{ $class->academicYear->name }})</option>@endforeach</select></div><div class="col-md-6"><label class="form-label" for="edit_student_section">Section</label><select class="form-select" id="edit_student_section" name="section_id"><option value="">Select section</option>@foreach($classes as $class)@foreach($class->sections as $section)<option value="{{ $section->id }}" @selected($record->section_id === $section->id)>{{ $class->name }} - Section {{ $section->name }}</option>@endforeach @endforeach</select></div><div class="col-12"><label class="form-label" for="edit_student_address">Address</label><textarea class="form-control" id="edit_student_address" name="address">{{ $record->address }}</textarea></div></div><button class="btn btn-sv mt-3">Save Student</button></form>
@elseif($type === 'teacher-edit')<form method="POST" action="{{ route('admin.teachers.update',$record) }}">@csrf @method('PUT')<div class="row g-3">@foreach([['name','Full Name','text',$record->user->name],['email','Email','email',$record->user->email],['phone','Phone Number','text',$record->user->phone],['qualification','Qualification','text',$record->qualification],['department','Department','text',$record->department],['experience_years','Experience (Years)','number',$record->experience_years]] as [$field,$label,$inputType,$value])<div class="col-md-6"><label class="form-label" for="edit_teacher_{{ $field }}">{{ $label }}</label><input class="form-control" id="edit_teacher_{{ $field }}" name="{{ $field }}" type="{{ $inputType }}" value="{{ $value }}"></div>@endforeach<div class="col-md-6"><label class="form-label" for="edit_teacher_joining">Joining Date</label><input class="form-control" id="edit_teacher_joining" name="joining_date" type="date" value="{{ $record->joining_date?->format('Y-m-d') }}"></div></div><button class="btn btn-sv mt-3">Save Teacher</button></form>
@elseif($type === 'parent-edit')<form method="POST" action="{{ route('admin.parents.update',$record) }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label" for="edit_parent_name">Full Name</label><input class="form-control" id="edit_parent_name" name="name" value="{{ $record->user->name }}" required></div><div class="col-md-6"><label class="form-label" for="edit_parent_email">Email</label><input class="form-control" id="edit_parent_email" name="email" type="email" value="{{ $record->user->email }}" required></div><div class="col-md-6"><label class="form-label" for="edit_parent_phone">Phone Number</label><input class="form-control" id="edit_parent_phone" name="phone" value="{{ $record->user->phone }}"></div><div class="col-12"><label class="form-label" for="edit_parent_address">Address</label><textarea class="form-control" id="edit_parent_address" name="address">{{ $record->address }}</textarea></div><div class="col-12"><label class="form-label" for="edit_parent_students">Linked Students</label><select class="form-select" id="edit_parent_students" name="student_ids[]" multiple>@foreach($students as $student)<option value="{{ $student->id }}" @selected($record->students->contains($student))>{{ $student->user->name }} - {{ $student->admission_number }}</option>@endforeach</select></div></div><button class="btn btn-sv mt-3">Save Parent</button></form>
@else<h2 class="h4">{{ $record->user->name }}</h2><p class="text-muted">{{ $record->user->email }} · {{ $record->user->phone ?: 'No phone' }}</p>@if($type === 'student')<dl class="row"><dt class="col-sm-4">Admission Number</dt><dd class="col-sm-8">{{ $record->admission_number }}</dd><dt class="col-sm-4">Class</dt><dd class="col-sm-8">{{ $record->schoolClass?->name }} {{ $record->section?->name }}</dd></dl><a class="btn btn-sv" href="{{ route('admin.students.edit',$record) }}">Edit Student</a>@elseif($type === 'parent')<dl class="row"><dt class="col-sm-4">Address</dt><dd class="col-sm-8">{{ $record->address ?: '-' }}</dd><dt class="col-sm-4">Children</dt><dd class="col-sm-8">{{ $record->students->pluck('user.name')->join(', ') ?: '-' }}</dd></dl><a class="btn btn-sv" href="{{ route('admin.parents.edit',$record) }}">Edit Parent</a>@endif
@endif
</div></div></section>
@endsection
